import PortalLayout from "./PortalLayout";
import { FileText, Download, Calendar, Receipt } from "lucide-react";

const REPORTS = [
  {
    icon: <FileText className="h-6 w-6 text-blue-600" />,
    title: "月结单",
    titleEn: "Monthly Statement",
    description: "包含当月所有交易记录、持仓及账户余额明细",
    descEn: "All transactions, holdings and balances for the month",
    available: false,
  },
  {
    icon: <Receipt className="h-6 w-6 text-violet-600" />,
    title: "税务报告",
    titleEn: "Tax Report",
    description: "年度资本利得及股息收入汇总，适用于税务申报",
    descEn: "Annual capital gains and dividend income summary for tax filing",
    available: false,
  },
  {
    icon: <Calendar className="h-6 w-6 text-emerald-600" />,
    title: "交易汇总",
    titleEn: "Transaction Summary",
    description: "自定义时间段内的交易汇总报告",
    descEn: "Customizable period transaction summary report",
    available: false,
  },
];

export default function PortalReports() {
  return (
    <PortalLayout>
      <div className="p-6 max-w-4xl mx-auto space-y-6">
        <div>
          <h1 className="text-2xl font-bold text-gray-900">报表 <span className="text-gray-400 font-normal text-lg">/ Reports</span></h1>
          <p className="text-sm text-gray-500 mt-1">下载您的账户报表与财务文件</p>
        </div>

        <div className="space-y-4">
          {REPORTS.map((report) => (
            <div key={report.titleEn} className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 flex items-start gap-4">
              <div className="flex-shrink-0 w-12 h-12 rounded-xl bg-gray-50 flex items-center justify-center">
                {report.icon}
              </div>
              <div className="flex-1 min-w-0">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <h2 className="text-base font-semibold text-gray-800">
                      {report.title} <span className="text-gray-400 font-normal">/ {report.titleEn}</span>
                    </h2>
                    <p className="text-sm text-gray-500 mt-1">{report.description}</p>
                    <p className="text-xs text-gray-400">{report.descEn}</p>
                  </div>
                  <button
                    disabled={!report.available}
                    className="flex-shrink-0 flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium border transition-colors disabled:opacity-40 disabled:cursor-not-allowed border-gray-200 text-gray-500 hover:bg-gray-50"
                  >
                    <Download className="h-4 w-4" />
                    下载 Download
                  </button>
                </div>
                {!report.available && (
                  <span className="inline-block mt-2 text-xs text-amber-600 bg-amber-50 border border-amber-100 rounded px-2 py-0.5">
                    暂无数据，账户激活后可下载 / Available after account activation
                  </span>
                )}
              </div>
            </div>
          ))}
        </div>

        <div className="bg-blue-50 border border-blue-100 rounded-xl p-4 text-sm text-blue-700">
          <p className="font-medium mb-1">报表生成说明 / About Report Generation</p>
          <p className="text-xs text-blue-600">月结单将于每月5日前自动生成。如需历史报表，请联系客服。<br />
          Monthly statements are generated by the 5th of each month. For historical reports, please contact support.</p>
        </div>
      </div>
    </PortalLayout>
  );
}
