// Vercel serverless entry.
// NOTE: do NOT import TypeScript sources from ../server/* here, because Vercel will
// only transpile api/* and Node ESM won't find ../server/_core/*.ts at runtime.
// Instead, reuse the bundled server handler generated by `pnpm run build`.

import coreHandler from "../dist/index.js";

export default function handler(req: any, res: any) {
  // When using Vercel rewrites to a single handler, preserve the original path.
  // vercel.json: /api/(.*) -> /api/index?path=$1
  const path = req?.query?.path;
  if (typeof path === "string" && path.length > 0) {
    const url = new URL(req.url, "http://localhost");
    url.searchParams.delete("path");
    req.url = `/api/${path}${url.search}`;
  }

  return coreHandler(req, res);
}

